config/routes.rb
Sfc::Application.routes.draw do
  resources :transactions

  get "account_transfer/index"

  resources :account_types

  resources :accounts

  root :to => "welcome#index"

end

app/models/account.rb
class Account < ActiveRecord::Base
  belongs_to :account_type
  has_many :transactions
  
  def balance
    initial_balance + (total_deposits - total_withdrawals)
  end
  
  def total_withdrawals
    transactions.where(:type => Transaction::WITHDRAWAL_TYPE).sum(:amount)
  end

  def total_deposits
    transactions.where(:type => Transaction::DEPOSIT_TYPE).sum(:amount)
  end
end

app/models/account_type.rb
class AccountType < ActiveRecord::Base
  has_many :accounts
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  WITHDRAWAL_TYPE = 'withdrawal'
  DEPOSIT_TYPE = 'deposit'

  scope :withdrawals, where(:type => WITHDRAWAL_TYPE)
  scope :deposits, where(:type => DEPOSIT_TYPE)
  
  def total_deposits
    deposits.inject(0) do |o,c|
      o.amount+c.amount
    end
  end
  
  def total_withdrawals
    withdrawals.inject(0) do |o,c|
      o.amount+c.amount
    end
  end
end

app/controllers/account_transfer_controller.rb
class AccountTransferController < ApplicationController
  def index
  end

end

app/controllers/account_types_controller.rb
class AccountTypesController < ApplicationController
  # GET /account_types
  # GET /account_types.xml
  def index
    @account_types = AccountType.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @account_types }
    end
  end

  # GET /account_types/1
  # GET /account_types/1.xml
  def show
    @account_type = AccountType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @account_type }
    end
  end

  # GET /account_types/new
  # GET /account_types/new.xml
  def new
    @account_type = AccountType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @account_type }
    end
  end

  # GET /account_types/1/edit
  def edit
    @account_type = AccountType.find(params[:id])
  end

  # POST /account_types
  # POST /account_types.xml
  def create
    @account_type = AccountType.new(params[:account_type])

    respond_to do |format|
      if @account_type.save
        format.html { redirect_to(@account_type, :notice => 'Account type was successfully created.') }
        format.xml  { render :xml => @account_type, :status => :created, :location => @account_type }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @account_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /account_types/1
  # PUT /account_types/1.xml
  def update
    @account_type = AccountType.find(params[:id])

    respond_to do |format|
      if @account_type.update_attributes(params[:account_type])
        format.html { redirect_to(@account_type, :notice => 'Account type was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @account_type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /account_types/1
  # DELETE /account_types/1.xml
  def destroy
    @account_type = AccountType.find(params[:id])
    @account_type.destroy

    respond_to do |format|
      format.html { redirect_to(account_types_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # GET /accounts
  # GET /accounts.xml
  def index
    @accounts = Account.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @accounts }
    end
  end

  # GET /accounts/1
  # GET /accounts/1.xml
  def show
    @account = Account.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @account }
    end
  end

  # GET /accounts/new
  # GET /accounts/new.xml
  def new
    @account = Account.new
    @account_types = AccountType.all

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @account }
    end
  end

  # GET /accounts/1/edit
  def edit
    @account = Account.find(params[:id])
  end

  # POST /accounts
  # POST /accounts.xml
  def create
    @account = Account.new(params[:account])

    respond_to do |format|
      if @account.save
        format.html { redirect_to(@account, :notice => 'Account was successfully created.') }
        format.xml  { render :xml => @account, :status => :created, :location => @account }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /accounts/1
  # PUT /accounts/1.xml
  def update
    @account = Account.find(params[:id])

    respond_to do |format|
      if @account.update_attributes(params[:account])
        format.html { redirect_to(@account, :notice => 'Account was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.xml
  def destroy
    @account = Account.find(params[:id])
    @account.destroy

    respond_to do |format|
      format.html { redirect_to(accounts_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  # GET /transactions
  # GET /transactions.xml
  def index
    @transactions = Transaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @transactions }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.xml
  def show
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/new
  # GET /transactions/new.xml
  def new
    @transaction = Transaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @transaction }
    end
  end

  # GET /transactions/1/edit
  def edit
    @transaction = Transaction.find(params[:id])
  end

  # POST /transactions
  # POST /transactions.xml
  def create
    @transaction = Transaction.new(params[:transaction])

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully created.') }
        format.xml  { render :xml => @transaction, :status => :created, :location => @transaction }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /transactions/1
  # PUT /transactions/1.xml
  def update
    @transaction = Transaction.find(params[:id])

    respond_to do |format|
      if @transaction.update_attributes(params[:transaction])
        format.html { redirect_to(@transaction, :notice => 'Transaction was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.xml
  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to(transactions_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/account_transfer_helper.rb
module AccountTransferHelper
end

app/helpers/account_types_helper.rb
module AccountTypesHelper
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/account_transfer/index.html.haml
%h1 AccountTransfer#index
%p Find me in app/views/account_transfer/index.html.haml

app/views/account_types/_form.html.haml
= form_for @account_type do |f|
  -if @account_type.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@account_type.errors.count, "error")} prohibited this account_type from being saved:"
      %ul
        - @account_type.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .actions
    = f.submit 'Save'

app/views/account_types/edit.html.haml
%h1 Editing account_type

= render 'form'

= link_to 'Show', @account_type
\|
= link_to 'Back', account_types_path

app/views/account_types/index.html.haml
%h1 Listing account_types

%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th

  - @account_types.each do |account_type|
    %tr
      %td= account_type.name
      %td= account_type.description
      %td= link_to 'Show', account_type
      %td= link_to 'Edit', edit_account_type_path(account_type)
      %td= link_to 'Destroy', account_type, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New account_type', new_account_type_path

app/views/account_types/new.html.haml
%h1 New account_type

= render 'form'

= link_to 'Back', account_types_path

app/views/account_types/show.html.haml
%p
  %b Name:
  = @account_type.name
%p
  %b Code:
  = @account_type.description

= link_to 'Edit', edit_account_type_path(@account_type)
\|
= link_to 'Back', account_types_path

app/views/accounts/_form.html.haml
= form_for @account do |f|
  -if @account.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :initial_balance
    = f.text_field :initial_balance
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :account_type
    = f.collection_select :account_type_id, AccountType.all, :id, :name
  .actions
    = f.submit 'Save'

app/views/accounts/edit.html.haml
%h1 Editing account

= render 'form'

= link_to 'Show', @account
\|
= link_to 'Back', accounts_path

app/views/accounts/index.html.haml
%h1 Listing accounts

%table
  %tr
    %th Name
    %th Initial balance
    %th Description
    %th Account type
    %th
    %th
    %th

  - @accounts.each do |account|
    %tr
      %td= account.name
      %td= account.initial_balance
      %td= account.description
      %td= account.account_type
      %td= link_to 'Show', account
      %td= link_to 'Edit', edit_account_path(account)
      %td= link_to 'Destroy', account, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New account', new_account_path

app/views/accounts/new.html.haml
%h1 New account

= render 'form'

= link_to 'Back', accounts_path

app/views/accounts/show.html.haml
%p
  %b Name:
  = @account.name
%p
  %b Initial balance:
  = @account.initial_balance
%p
  %b Description:
  = @account.description
%p
  %b Account type:
  = @account.account_type.name
%p
  %b Current Balance 
  = @account.balance

= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', accounts_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Sfc
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    .home 
      %a{:href => "/"} Home
    #app
      = yield

app/views/transactions/_form.html.haml
= form_for @transaction do |f|
  -if @transaction.errors.any?
    #errorExplanation
      %h2= "#{pluralize(@transaction.errors.count, "error")} prohibited this transaction from being saved:"
      %ul
        - @transaction.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :amount
    = f.text_field :amount
  .field
    = f.label :date
    = f.date_select :date
  .field
    = f.label :transaction_type
    = f.text_field :transaction_type
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :type
    = f.text_field :type
  .actions
    = f.submit 'Save'

app/views/transactions/edit.html.haml
%h1 Editing transaction

= render 'form'

= link_to 'Show', @transaction
\|
= link_to 'Back', transactions_path

app/views/transactions/index.html.haml
%h1 Listing transactions

%table
  %tr
    %th Amount
    %th Date
    %th Transaction type
    %th Description
    %th Type
    %th
    %th
    %th

  - @transactions.each do |transaction|
    %tr
      %td= transaction.amount
      %td= transaction.date
      %td= transaction.transaction_type
      %td= transaction.description
      %td= transaction.type
      %td= link_to 'Show', transaction
      %td= link_to 'Edit', edit_transaction_path(transaction)
      %td= link_to 'Destroy', transaction, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New transaction', new_transaction_path

app/views/transactions/new.html.haml
%h1 New transaction

= render 'form'

= link_to 'Back', transactions_path

app/views/transactions/show.html.haml
%p
  %b Amount:
  = @transaction.amount
%p
  %b Date:
  = @transaction.date
%p
  %b Transaction type:
  = @transaction.transaction_type
%p
  %b Description:
  = @transaction.description
%p
  %b Type:
  = @transaction.type

= link_to 'Edit', edit_transaction_path(@transaction)
\|
= link_to 'Back', transactions_path

app/views/welcome/index.html.haml
#welcome 
  %span Welcome to
  %span.sfc Simple Financial Control
#menu
  %ul
    %li= link_to "Account", accounts_path
    %li= link_to "Account Types", account_types_path